export const ToyData=[
    {
        ToyId:"T006",
        ToyImg:"https://m.media-amazon.com/images/I/614gFRpdhSL._AC_SX679_.jpg",
        ToyName:"Iron Man",
        ToyCost:2600,
        ToyRating:4.9,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T001",
        ToyImg:"https://rukminim2.flixcart.com/image/612/612/xif0q/action-figure/i/m/d/4-spider-man-across-the-spider-verse-scarlet-spider-toy-for-kids-original-imagmemufuzjyu7g.jpeg?q=70",
        ToyName:"Spider-Man",
        ToyCost:749,
        ToyRating:3.6,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T011",
        ToyImg:"https://rukminim2.flixcart.com/image/850/1000/kqidx8w0/action-figure/q/u/v/thor-avengers-action-figures-avengers-toys-set-6-inch-superheros-original-imag4g8cfpqgw2sd.jpeg?q=90&crop=false",
        ToyName:"THOR",
        ToyCost:2399,
        ToyRating:4.6,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T007",
        ToyImg:"https://rukminim2.flixcart.com/image/416/416/kz065jk0/action-figure/j/g/6/3-super-hero-s-die-cast-metal-action-figure-captain-america-with-original-imagb47q3cmyhkup.jpeg?q=70&crop=false",
        ToyName:"captain America",
        ToyCost:849,
        ToyRating:3.9,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T014",
        ToyImg:"https://images-cdn.ubuy.ae/65977f520c57eb15850ab26d-marvel-legends-series-doctor-strange-in.jpg",
        ToyName:"Doctor Strange",
        ToyCost:2299,
        ToyRating:4.6,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T003",
        ToyImg:"https://rukminim2.flixcart.com/image/612/612/k7tdj0w0/action-figure/g/x/y/avengers-titan-hero-series-blast-gear-deluxe-hulk-action-figure-original-imafpzfav6zh7jav.jpeg?q=70",
        ToyName:"Hulk",
        ToyCost:809,
        ToyRating:3.8,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T005",
        ToyImg:"https://rukminim2.flixcart.com/image/612/612/xif0q/action-figure/c/j/e/4-groot-9-5-inch-scale-action-figure-marvel-24-original-imagthm89z8v7qmr.jpeg?q=70",
        ToyName:"Groot",
        ToyCost:699,
        ToyRating:3.9,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T012",
        ToyImg:"https://m.media-amazon.com/images/I/61fWFhH7T+S.jpg",
        ToyName:"LOKI",
        ToyCost:1200,
        ToyRating:4.4,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T002",
        ToyImg:"https://rukminim2.flixcart.com/image/612/612/xif0q/action-figure/d/d/z/3-black-panther-avengers-action-figure-toy-18-cm-littlin-18-original-imaghaw64yzz4ayr.jpeg?q=70",
        ToyName:"Black Panther",
        ToyCost:2270,
        ToyRating:4.7,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T015",
        ToyImg:"https://m.media-amazon.com/images/I/71SrcMbUMDL.jpg",
        ToyName:"Hawkeye",
        ToyCost:1899,
        ToyRating:4.4,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T004",
        ToyImg:"https://m.media-amazon.com/images/I/513D+eu+YnL._AC_UF1000,1000_QL80_.jpg",
        ToyName:"black widow",
        ToyCost:1149,
        ToyRating:4.2,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T008",
        ToyImg:"https://m.media-amazon.com/images/I/81CUh9T-38L._AC_UF1000,1000_QL80_.jpg",
        ToyName:"Falcon",
        ToyCost:2519,
        ToyRating:4.8,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T010",
        ToyImg:"https://i.ebayimg.com/images/g/hxQAAOSwgiplKUFe/s-l400.jpg",
        ToyName:"Rocket Raccoon",
        ToyCost:1459,
        ToyRating:4.3,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T016",
        ToyImg:"https://fatcatcollectibles.in/cdn/shop/files/12914459-4754846149182466.jpg?v=1693741418&width=2048",
        ToyName:"Scarlet",
        ToyCost:1399,
        ToyRating:4.2,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T017",
        ToyImg:"https://m.media-amazon.com/images/I/614lo1hb7gL._AC_UF894,1000_QL80_.jpg",
        ToyName:"james rhodes",
        ToyCost:2859,
        ToyRating:4.9,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T018",
        ToyImg:"https://infinitycollectables.com/cdn/shop/products/hr_hasf1409_h.jpg?v=1677286775&width=1080",
        ToyName:"peter quill",
        ToyCost:1600,
        ToyRating:4.1,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T019",
        ToyImg:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6562/6562836_sd.jpg",
        ToyName:"ANT MAN",
        ToyCost:1899,
        ToyRating:4.4,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T020",
        ToyImg:"https://toysnowman.com/cdn/shop/files/F6537_PROD_AVN_LEGENDS_MINUS_A4_0006_2000px_300DPI_700x700.jpg?v=1691600224",
        ToyName:"Nick Fury",
        ToyCost:1799,
        ToyRating:4.2,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T013",
        ToyImg:"https://rukminim2.flixcart.com/image/416/416/xif0q/action-figure/q/3/4/5-hulkbuster-iron-man-action-figure-20-cm-collectible-for-office-original-imagh2zhvgtmkan2.jpeg?q=70&crop=false",
        ToyName:"Iron Hulk",
        ToyCost:2650,
        ToyRating:4.8,
        ToyLike:false,
        ToyCart:false,
    },
    {
        ToyId:"T009",
        ToyImg:"https://rukminim2.flixcart.com/image/416/416/xif0q/action-figure/h/l/s/5-super-villain-thanos-action-figure-toyeez-21-original-imagzxmyrgfecaam.jpeg?q=70&crop=false",
        ToyName:"Thanos",
        ToyCost:2145,
        ToyRating:4.7,
        ToyLike:false,
        ToyCart:false,
    },
]






